alias cp='cp -i'
alias mv='mv -i'
alias t='telnet'
alias s='ssh'
alias p='ping'
alias v='vim'
alias h='history'
alias ls='ls --color=auto'
alias ll='ls -alh'
alias grep='grep --color'
alias pinf='ping -i 0.2'
alias pinb='ping -s 9000'
alias p10='sudo ping -c 10 -i 0.02'
alias p100='sudo ping -c 100 -i 0.02'
alias update='sudo apt-get update'
alias upgrade='sudo apt-get upgrade'
alias install='sudo apt-get install'
alias cache='sudo apt-cache'
